### PR TITLE
Add function to get string errors from error numbers

### PR DESCRIPTION
**Pull request by markzz**
Add trace_get_errstr() the takes in an error number and returns a string
representation of the error number provided.

Let me know if the placement of the function or anything else needs to change.

### CODE REVIEW

**Comment by markzz** [comment]
Force pushed a revised commit with suggested changes.

**Comment by salcock** [comment]
Your push doesn't appear to have changed anything (at least from my perspective). The original problems I commented on are still present -- this is also the case if I look at https://github.com/markzz/libtrace/blob/develop/lib/trace.c directly.

**Comment by markzz** [comment]
Oh you're right, I must've not added the files properly.

**Comment by markzz** [comment]
Should be all set now.

**Pull request merged**
